### ISSUE TITLE
initialize repo

### ISSUE THREAD

**Issue by LGro** [sciencefair-land/sciencefair-datasource-arxiv#1]
@blahah, please initialize/configure this repo in a way such that I can fork it and make a pull request

**Comment by blahah** [comment]
@lgro my apologies - I intended to do this immediately and put my initial experiment code in the repo, but have been busy with other work this week. Good news is that going forward I will have 50% of my time dedicated to ScienceFair, so this should be the last week when I am generally unable to make progress on this.

It's 2am here (EAT), so tomorrow morning I will initialise and push my code.

Also, thanks so much for your interest :) I think this is the first time I've ever seen a repo where someone wanted to PR before it was initialised!

**Comment by LGro** [comment]
Don't worry and good to hear about your additional resources :)
I currently have a python script downloading and extracting the source files of all papers from a given category. I'll be happy to see how I can add to what you already prepared.

**Comment by bencevans** [comment]
@LGro @blahah may either of you still have your progress stored somewhere? would be interested to see what you got and maybe take it further.

**Comment by LGro** [comment]
This is what I retrieved from a backup from back then. It's very preliminary :sweat_smile: 

However, there were some legal issues regarding science-fair serving arxiv content, since only a subset of the publications there are actually under some proper creative commons license that allow redistribution. @blahah can further elaborate on this.

```python
# requires to have latexml in your PATH, gunzip, tar
# requires Python3 and packages: lxml, urllib, subprocess
#   (TODO: add dependencies text to install)
# have pandoc-jats at the same level as this project directory
# (i.e. accessible via ../pandoc-jats)
# pandoc and pandoc-citeproc

import xml.etree.ElementTree
import urllib.request
from subprocess import call
import os

def download(url, file):
	data = urllib.request.urlopen(url).read()

	# save as file.gz, seems necessary since gunzip doesn't extract files
	# without .gz suffix
	with open(file+'.gz', 'wb') as out:
		out.write(data)

	# save as file.tar
	with open(file+'.tar', 'wb') as out:
		out.write(data)

# TODO: replace with commandline argument (without ending slash) and take care
# that extraction of source archive ends up in that directory as well
working_dir = '.'

# TODO: replace with argument for script or iterate over list of all categories
query = 'cat:cs.AI'

# TODO: imporive error return code handling
#   (also see http://tldp.org/LDP/abs/html/index.html)
error_return_codes = [1, 2, 126, 127, 128, 255]

#init entry collection entries(? check datatype) non empty
entries = (1)

# define how many search results should be processed at once
search_offset_step = 10

# initial search offset
search_offset = 0

# as long as there are entries, continue to search for the next
# search_offset_step results
while entries:

	# get search_offset_step amount of results for the given search query
	arxiv_url = 'http://export.arxiv.org/api/query?search_query={}&start={}\
				&max_results={}'.format(query, search_offset, search_offset_step)
	data = urllib.request.urlopen(arxiv_url).read().decode('utf-8')
	e = xml.etree.ElementTree.fromstring(data)

	# TODO: store all <entry> elements in entries
	entries = e.findall('{http://www.w3.org/2005/Atom}entry')

	for entry in entries:
		# get <id> and extract part after last slash
		# (e.g. 0102536v1 from http://arxiv.org/abs/cond-mat/0102536v1)
		arxiv_publication_url = entry.find('{http://www.w3.org/2005/Atom}id')
		arxiv_id = arxiv_publication_url.text.split('/')[-1]
		print(arxiv_id)

		# create source URL with extracted info from id
		# (e.g. https://arxiv.org/e-print/hep-th/9901001v3)
		arxiv_source_url = 'https://arxiv.org/e-print/hep-th/{}'.format(arxiv_id)

		# download source file to working directory and name after arxiv_id
		source_file = '{}/{}'.format(working_dir, arxiv_id)

		download(arxiv_source_url, source_file)

		# create directory to extract content to
		if not os.path.exists(working_dir + '/' + arxiv_id):
			os.makedirs(working_dir + '/' + arxiv_id)

		# try gunzip in temp directory with force flag to automatically
		# overwrite existing files
		# TODO: check if the output file really always is a single LATEX file
		extraction_target = '{}/{}/{}.tex'.format(working_dir, arxiv_id, arxiv_id)
		with open(extraction_target, 'w') as outfile:
			response = call(['gunzip', '-f', '-c', source_file+'.gz'],
				stdout=outfile)

		# if gunzip fails, try tar -xvf
		if response in error_return_codes:
			response = call(['tar', '-xvf', source_file+'.tar', '--directory', extraction_target])
			print('tar response: ', response)

			# if gunzip and tar fail, check if latex source file
			if response in error_return_codes:
				# TODO: check if latex source file all along and copy to target dir in that case (is that a realistic scenario?!)
				print('ERROR: All attempts to extract {} failed.'.format(arxiv_id))

		# find tex root file without file suffix (is that always <id>.tex ?)
		root_file = source_file

		entries = ()
		break

		# convert with pandoc
		call(['pandoc', '{}.tex'.format(root_file), '--filter',
			'pandoc-citeproc', '-t', 'jats.lua', '-o', 'example1.xml',
			'--template=default.jats', '--bibliography=example.bib',
			'--csl=jats.csl'])

		# TODO: check for additional errors and take consequences, like specific
		# log messages or a summary of (un-)successful conversions

	search_offset += search_offset_step
```

**Comment by bencevans** [comment]
nice! I started trying to do the conversion too. so far been trying to use latexml by itself but proving difficult with the XML->JATS conversion. maybe I'll switch over to letting pandoc sort it. i've pushed up my progress to https://github.com/bencevans/arxiv-to-xml

**Comment by blahah** [comment]
Hey, so I got this working back when I made the repo and was working in a remote location, then had a catastrophic laptop failure before I could push.

see https://twitter.com/blahah404/status/883129664331534336

I still have the broken laptop with the code on 😬I'll see if I can recover it, otherwise I'll restart from scratch (important anyway probably since JATS and Substance have changed a lot).
